"""FR-12, row 15: the drafts the grounding guardrail refused, laid out to be read.

    uv run python scripts/grounding_review.py

Writes `evaluation/reports/grounding_review.md`. The gate run answers 41% of validation tickets
and the grounding check refuses 25 of the 58 drafts that reach it, so **this one check is the
biggest remaining lever on the answer rate** — bigger than the confidence threshold. Whether those
refusals are the guardrail being strict or the drafts being unsupported is a judgement about
answer quality, and it is the author's to make, not the system's.

So this script decides nothing. For each refused draft it shows the ticket, the sentences the
model wrote, each sentence's content-word overlap with the retrieved passages, what PR-03 said
and the words it quoted, and the passages themselves — everything needed to say "the guardrail
was right" or "the guardrail was wrong" and nothing more.

Replies come from the response cache, so re-reading costs nothing.
"""
from __future__ import annotations

import argparse
from pathlib import Path

from ticketing_agent.classify import IntentClassifier, TrainedClassifier
from ticketing_agent.config import load_settings
from ticketing_agent.generate import Drafter
from ticketing_agent.guardrails import (
    OVERLAP_THRESHOLD,
    GroundingJudge,
    Guardrails,
    is_claim,
    overlap,
    split_sentences,
)
from ticketing_agent.ingest import load_tickets
from ticketing_agent.provider import ProviderClient, ProviderFailure
from ticketing_agent.retrieve import Retriever
from ticketing_agent.route import Router

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_REPORT = ROOT / "evaluation" / "reports" / "grounding_review.md"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", required=True, help="the ticket file the gate run used")
    parser.add_argument("--output", default=str(DEFAULT_REPORT))
    parser.add_argument("--limit", type=int, default=None)
    args = parser.parse_args()

    settings = load_settings()
    retriever = Retriever(settings)
    retriever.build_index(settings.require_path("docs_path"))
    client = ProviderClient(settings)
    classifier = IntentClassifier(TrainedClassifier.load(settings.classifier_path))
    router, drafter = Router(settings), Drafter(client)
    guardrails = Guardrails(judge=GroundingJudge(client))

    tickets = load_tickets(Path(args.input))[: args.limit]
    cases: list[dict] = []
    for ticket in tickets:
        if ticket.is_malformed:
            continue
        passages = retriever.search(ticket.text, threshold=settings.relevance_threshold)
        decision = router.decide(ticket, classifier.classify(ticket), passages)
        if decision.escalated:
            continue
        try:
            draft = drafter.draft(ticket, passages)
        except ProviderFailure:
            continue
        if not draft.usable:
            continue
        report = guardrails.check_draft(
            ticket=ticket, reply=draft.reply,
            sentences=tuple((s.text, tuple(s.citations)) for s in draft.draft.sentences),
            retrieved=passages, citations=draft.citations,
            confidence=decision.confidence, threshold_applied=decision.threshold_applied)
        grounding = next(r for r in report.results if r.name == "grounding")
        if grounding.passed:
            continue
        cases.append({"ticket": ticket, "draft": draft, "passages": passages,
                      "detail": grounding.detail})
        print(f"  {ticket.ticket_id}: refused — {grounding.detail[:80]}")

    out = Path(args.output)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(_render(cases, len(tickets), args.input), encoding="utf-8")
    print(f"\n{len(cases)} refused drafts written to {_relative(out)}")
    return 0


def _render(cases: list[dict], tickets: int, source: str) -> str:
    lines = [
        "# The drafts the grounding guardrail refused (FR-12)",
        "",
        f"{len(cases)} refusals over {tickets} tickets from `{source}`. Generated by",
        "`scripts/grounding_review.py`, which **decides nothing**: the question is whether each",
        "refusal was right, and that is the author's judgement.",
        "",
        "For each one: what the model wrote, how much of each sentence's content appears in the",
        f"retrieved passages (the floor is {OVERLAP_THRESHOLD}), and what PR-03 said. A sentence can",
        "clear the arithmetic floor and still be refused by the judge, and that combination is the",
        "one worth reading closely — it is where the two halves of the check disagree.",
        "",
        "**How to read a case.** If the refused sentence says something the passages do not, the",
        "guardrail was right and the draft was unsupported. If it says something the passages do",
        "say, in different words, the guardrail was strict and the cost is a ticket a person now",
        "has to answer.",
        "",
    ]
    for case in cases:
        ticket, draft = case["ticket"], case["draft"]
        support = " ".join(p.text for p in case["passages"])
        lines += [
            "---",
            "",
            f"## {ticket.ticket_id} · {ticket.channel} · {ticket.subject or '(no subject)'}",
            "",
            f"> {' '.join((ticket.body or '').split())[:400]}",
            "",
            f"**Refused because:** {case['detail']}",
            "",
            "| overlap | claim? | sentence |",
            "|---|---|---|",
        ]
        for sentence in split_sentences(draft.draft.text):
            score = overlap(sentence, support)
            flag = "**below floor**" if (is_claim(sentence) and score < OVERLAP_THRESHOLD) else (
                "claim" if is_claim(sentence) else "exempt")
            lines.append(f"| {score:.2f} | {flag} | {' '.join(sentence.split())[:150]} |")
        lines += ["", "**Passages it was allowed to use:**", ""]
        for passage in case["passages"]:
            lines.append(f"- `{passage.chunk_id}` — {' '.join(passage.text.split())[:220]}")
        lines.append("")
    if not cases:
        lines.append("No refusals in this sample.")
    return "\n".join(lines) + "\n"


def _relative(path: Path) -> str:
    try:
        return str(path.resolve().relative_to(ROOT))
    except ValueError:
        return str(path)


if __name__ == "__main__":
    raise SystemExit(main())
